name: XQuartz Install Test
on: [push]
      
jobs:
  build:
    runs-on: macOS-10.15
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install pandoc and pandoc citeproc
        run: |
          brew install pandoc
          brew install pandoc-citeproc
      - name: Install XQuartz for rayrender
        run: |
          brew cask install xquartz
      - name: Install Packages
        run: |-
          Rscript -e "install.packages('devtools')"
          Rscript -e "devtools::install_github('tylermorganwall/rayshader')"
